version: "3.7"
services:
  backend:
    restart: always
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - api-net

  frontend:
    restart: always
    container_name: frontend
    command : ionic serve
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - api-net

networks:
  api-net:
    driver: bridge