# Generated by Django 3.2.9 on 2022-01-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venues_yelp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venues',
            old_name='yelp',
            new_name='vibes',
        ),
        migrations.AddField(
            model_name='venues',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
    ]
