# Generated by Django 3.2.9 on 2022-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20220103_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='images',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venues',
            name='price',
            field=models.CharField(default='?', max_length=5),
            preserve_default=False,
        ),
    ]
