# Generated by Django 3.2.9 on 2022-01-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20220104_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='deals',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
