# Generated by Django 3.2.9 on 2022-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_bars_rated',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vibe_votes',
            field=models.JSONField(null=True),
        ),
    ]
