# Generated by Django 3.2.9 on 2022-06-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220610_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lng',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
